project:
  type: website

website:
  title: "Charlie Hoose"
  navbar:
    background: "#0d1117"
    foreground: "#c9d1d9"
    left:
      - href: index.qmd
        text: About
      - href: research_work.qmd
        text: Research & Work Experience
      - href: projects.qmd
        text: Projects
  page-footer:
    background: "#0d1117"
    center: "© 2025 Charlie Hoose"

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: false
    smooth-scroll: true
    page-layout: full
