---
title: "Work and Research Experience"
---

# Work Experience

## Data Analyst Intern: First Citizens Bank

From June 2025 until present, I have been a Data Analyst Intern for First Citizens Bank in the Data Reporting Team under Community Affairs. My main responsibilities fall under the Community Reinvestment and Affairs category, as I mainly work with philanthropy and donation data. I regularly create and validate monthly dashboards and reports of philanthropic donations and service hours of the bank. This includes working heavily within Tableau, PowerBI, Excel, and SAS. I have created many efficiencies within this reporting, including creating automatic color-coding based on our gap-to-goals using Excel VBA. This process originally took about 45 minutes per dashboard, with room for human error, however it is now always 100% correct and takes less than a minute to color a report. I also have worked in reconciliation, identifying incorrect or forgotten payments across various software systems. I created a system to identify erroneous instances with 97% accuracy automatically, saving over 90% of manual processing time. Moreover, over last summer, I spearheaded an intern project proposing a bank-wide philanthropic strategy, analyzing historic and projected donations and bank statements in both Excel and Tableau. I presented this to over 60 employees, including some at the highest level. Moreover, I also have utilized Microsoft Power Automate to maximize SharePoint usage for data intake requests, automatically alerting a chain of approval to approve any new requests. On a day-to-day level, I mainly help with any data or reporting needs from my team or from Ad Hoc reporting across the bank. Whether it be pulling certain data or information using SQL or creating visualizations in Excel, I help the bank further understand its own levels of giving and holdings. 

This current role has been extremely important for me because of the work I am able to do. By working under the Community Affairs umbrella, I am able to directly identify gaps in my bank's donations, volunteering, and giving, primarily to Low-to-Moderate Income areas. I am able to improve our ability to equitably lend and donate to various regions and nonprofits, as well as identify volunteering needs. This work goes much beyond just creating data reports, but with helping my community and communities afar. I am able to impact people's lives in a beneficial way, even if indirectly, on a large scale. This ultimately resonates with my own internal goals of putting in more good in the world than I take out. I feel it to be my responsibility to try to enact positive change, and I am very grateful to be in a role where I can accomplish this. 

I plan on starting as a Business Analyst with the bank in the Rotational Analytics Team after I graduate UCLA in June 2026.

## Data Scientist: Italian National Baseball Team (World Baseball Classic)

As part of a consulting class at UCLA, I had the opportunity to collaborate with the Italian National Baseball Team during the World Baseball Classic from January to March of 2026. My team's primary goal for this was to develop matchup predictions for each batter-pitcher combination that the team would potentially face in the tournament. I, along with my team, developed an R Shiny application to model this exact request. We conducted extensive literature review to identify what other models looked like, and we found that random forest and Log5 models worked somewhat well. After scraping all of the MLB and AAA pitch-level data from 2020-2024, we created a XGBoost leveraging the Log5 formula to predict the delta run expectancy for each at-bat-matchup. Some of the variables that had the most weight and importance on the model was pitcher and batter platoon effects, strikeout advantage, walk rate, and individual types of pitches used. There was also a deduction in expectancy depending on the level of the batter/pitcher (minor vs major league). Our metric was centered around 100, where that would indicate a fair matchup, with lower scores being better for the pitcher, and higher scores better for the batter.

When validated on the 2024 MLB season as a validation set, this model achieved a correlation of around 0.4, which was significantly better than what our literature review found (correlation of about 0.1). Moreover, by comparing OPS (on-base plus slugging) to our delta run expectancy, we found significant results when bucketing the DREs. By grouping all values within a range of 5 (i.e., 85-90, 90-95, 95-100, etc.), there was a correlation of 0.96, indicating that our metric is extremely correlated with OPS. This confirms the accuracy of the model.

This model was presented within the application, creating easy matchup charts for selectable batters and pitchers, or presets for the Italian team against their scheduled opponents. We had regular meetings with staff of the Italian team, and were able to send them our results, teach them how to use the application, and further tune our model and app to their requests. After the WBC ended, the model had a 0.97 OPS bucketed-correlation and an overall correlation of 0.46 using the WBC pitch-level data as a test set. Once again, this shows the effectiveness of our results. Ultimately, this provided useful data to the team, who ended up using this to determine batting orders and pitcher decisions in a tournament where they were the underdogs. Despite being in a stacked pool with USA and Mexico, the Italian team not only went undefeated, but made their way to the semifinals, much better than anyone was predicting. You can find the application [here](https://jjsvenson.shinyapps.io/Italy-Matchup-Model/) or on my GitHub. 

# Research Experience

## Data Science Research Intern: WISE

In my time at UCLA, I was able to work in the B John Garrick Institute for Risk Sciences as a Research Intern. I was an intern from April 2024 to July 2025. I contributed to an app, WISE (**WI**ldfire **S**afe **E**gress), which focused on optimizing and predicting the evacuation of a community/area given a wildfire situation. By using Bayesian Statistics, WISE uses data on population demographics, densities, and road network capacities, bottlenecks, etc. to predict how long or how many people will be able to evacuate for a wildfire in a given time. It can be used by city planners to rethink how they build new roads or where to allocate funds for rebuilding, or by situation unit leaders on wildfire teams to optimize getting civilians to safety.

Within the team, I used my data science knowledge to do various case studies on wildfires in the past, presenting data and plots of historic trends. I also created many analyses of different, rival software and novel programs in order to better our application. Most notably, I created a RAG process that would extract keywords from research papers relating to wildfire and evacuation to identify different variables and their importance. This was used to improve the evacuation model used to decide when people leave in the application, strengthening the app's usability and accuracy. It was also able to significantly speed up the synthesis of research papers by another coworker, who was improving the evacuation model and needed a way to identify which factors most influence a person's evacuation speed, roadblocks, etc.

This work once again reinforces my desire to bring more good to humanity through data science. By using my knowledge to improve a wildfire evacuation app, I know that I am contributing to a better society and could potentially help save lives. I truly believe that it is our responsibility to uplift and improve the lives of others, so being apart of this research is very important to me.

You can read more about WISE [here](https://www.risksciences.ucla.edu/crse-software-blog/2023/11/13/wise).


